### ISSUE TITLE
Change session viewer default filter range

### ISSUE THREAD

**Issue by MikeMaximus** [MikeMaximus/gbm#116]
The session viewer currently defaults to show all stored sessions.  This could get slow and annoying once there's a lot of data.  

Not sure exactly what I want to do here yet, maybe default to the current month.

**Comment by basxto** [comment]
Maybe an external tool would be better for this. It would probably make GBM too blown up and complex.

I mean storing the data isn’t much, it just needs some space.

That’s the reason, why I started a program, that will just do the tracking. With plans for a backup and a playing stats tool. But I want to focus more on backing up all games found on the disk instead of the last running, so that you can integrate it into a regular backup script. (I usually skip the steam folder)

**Comment by MikeMaximus** [comment]
I don't think I'm going to make the session viewer any more complex than it is now, the only other enhancement I was thinking of is a simple export if anyone wants to do something more advanced with the data.

A program for backing up all games at once is nice.  GameSave Manager has that covered on Windows, but I imagine there probably isn't any alternative for Linux.

**Comment by basxto** [comment]
I just wonder how much data programs should share.

Sharing the database, would need some agreements and planning regarding the format. I’m doing that for now, but I will most likely change that. I can already create my own database from GBM’s XML game lists. Exporting is definitely slower.

For sharing it would be necessary to identify games uniquely by as many already existing handles as possible https://github.com/basxto/gamesPy/blob/master/roadmap.md#07
Otherwise you’d have trouble to match savegames and sessions with games.
No database is exhaustive, but would allow to get additional information about a game or associate sessions with a game manager.

I don’t know if it could happen that one uses different savegame managers, but it would definitely be practical to also include an export of that game’s data into the backup. Right now you are doing that with the database located in the backup folder, right?

I should divide that into issues.

**Comment by basxto** [comment]
Back to topic: Last 30 days or last week would be handy

**Comment by MikeMaximus** [comment]
The form now defaults to show 7 days from the last recorded session. 

For example,  if the last recorded session was December 27th,  the form will default to December 20th to December 27th.
