### ISSUE TITLE
[Request] Automatically extract icons from executable file

### ISSUE THREAD

**Issue by Gantzyo** [MikeMaximus/gbm#142]
Basically title. Extracting icons from exes, dlls, or any file is kinda easy using VB (Icon.ExtractAssociatedIcon(filePath)), so, would it be viable to automatically perform this task?

As an addition, some executables store multiple icons so how about a prompt asking for "Do you want to extract icons from EXE file?" ? If user says yes GBM could store each icon as PATH_TO_EXE/GBM_GAME_ID_SIZE.ico, example: PATH/71e5dcb7-5ba9-411c-9135-95f7da391195_x16.ico, PATH/71e5dcb7-5ba9-411c-9135-95f7da391195_x32.ico, PATH/71e5dcb7-5ba9-411c-9135-95f7da391195_x64.ico...

Thanks for your time and thanks for this awesome software!

**Comment by MikeMaximus** [comment]
I'm glad you like it. 👍 

But I'm not sure this request is in the scope of the project, there's already many utilites to accomplish extracting icons in both Windows and Linux.  Is there a specific reason you think GBM should do this?

**Comment by Gantzyo** [comment]
In my opinion, it's inconsistent that GBM can't get the default icon (exe's icon) while I'm able to manually set one.

Obviously, this is something completely secondary and not needed at all.

**Comment by MikeMaximus** [comment]
Ah well I can understand that, there are situations when I'd want to set the display icon in GBM to the exe icon, and GBM could save a step there fairly easily.

There is a change I want to make with how GBM handles displaying the detected game icon I could tie this into.  I'll see when I start working on the next release.

**Comment by MikeMaximus** [comment]
It looks like playnite grabs it's data from igdb.com, api access is only free up to a point however.  It would be nice to optionally pull down icons and information for Linux.  The Company, Version and Icon fields are mainly there for Linux, since I can't pull them from the executable on that OS.  I'll create another issue for this if it's something I want to do.

**Comment by basxto** [comment]
I’ll open an issue where I gather links to related freedesktop.org-specifications for importing .desktop-files by drag and drop. The most complex thing is likely finding the right path, but they even have pseudo code for getting icons.
So you have a starting point if you want to implement that. It‘s a feature that just never mattered to me.

**Comment by MikeMaximus** [comment]
The next version of GBM will be automatically extracting the executable icons as a 32x32 bitmap to the %localappdata%\gbm folder when the process is detected.  This is mainly to stop GBM from keeping an open file handle on detected executables, but the files will be there if you want to do anything else with them.

Unfortunately that is as far as i'm going to go, the ExtractAssociatedIcon function is garbage.  It can only handle 32x32 and causes color corruption when saving as an ico type.  To properly handle multiple icons, sizes, etc. I'd need to write a Win32 COM interface, which I don't want to do.

**Comment by MikeMaximus** [comment]
I've decided to remove the icon extraction feature from the upcoming release of GBM.  I'm not happy with my half-assed implementation.  Since I can't put in the effort to do this well, I would rather leave this up to other dedicated apps.

While working on this issue i've made other optimizations and fixes to how GBM deals with icons that will still be included in the next release.
