### ISSUE TITLE
Wine/Proton game detection failures

### ISSUE THREAD

**Issue by MikeMaximus** [MikeMaximus/gbm#149]
In some cases, games running in Wine aren't being detected.

This is happening because wine-preloader is sometimes referring to the windows executable using a host system path in the call parameter instead of a path within the prefix.

For example, it's using /home/mike/.wine-prefix/drive_c/game/gamebinary.exe instead of C:\game\gamebinary.exe

When I first implemented detecting wine games all my tests cases came back with a prefix path, so it was designed to parse a windows path.

A fix for this will be included in the upcoming changes for issue #148.

**Comment by basxto** [comment]
This appears to happen, when you start wine with a unix path.
It will be hard to find out whether it’s a unix or windows path.
Wine accepts `/` and `\` for both, even though unix is usually with `/` and windows is usually with `\`.
Distinguishing absolute paths should works, since unix always starts with `/` and windows starts like `Z:\`.
For relative paths the format does not matter, since they are always relative to the current working directory of the process. It makes no difference whether you started something with a relative path or whether a process starts another process within wine with a relative path.

**Comment by MikeMaximus** [comment]
I just need to know what to split the path string with so I can find the process name.  I'm testing which slash is being used first now instead of assuming it's a backslash, which I shouldn't have been doing regardless.

I think I was using PlayOnLinux to test this initially, which was likely always starting wine with a Windows path.

**Comment by MikeMaximus** [comment]
Good idea, i'll do the replace and always use / so it can't break on a mixed notation path.

**Comment by MikeMaximus** [comment]
This should be good now and will get more testing before next release.  Thanks for the help basxto.
