### ISSUE TITLE
Different variable handling

### ISSUE THREAD

**Issue by basxto** [MikeMaximus/gbm#152]
It would be better to to keep variables unchanged, after all they can be pasted into a file manager without a problem.
Games that use variables behave differently from those, who use hard coded paths, but gbm can’t distinguish them.
`%USERPROFILE%` and `~` is the only one, where I would urge the user to replace fixed paths with variables.
Right now it’s also not easily  possible to copy paths directly from the XML or website.

On Windows:
* `%USERPROFILE%`
* `%APPDATA%`
* `%LOCALAPPDATA%`
* `%COMMONDOCUMENTS%`

For linux only `~` works in file managers, but the rest can work in terminals.

On Linux:
* `~` (`Personal` in Mono)
* `${XDG_DATA_HOME:-~/.local/share}` (`LocalApplicationData` in Mono)
* `${XDG_CONFIG_HOME:-~/.config}` (`ApplicationData` in Mono)

It would make sense to automatically replace `${HOME}` and `$HOME` with `~`, `${XDG_DATA_HOME}` and `$XDG_DATA_HOME` with `${XDG_CONFIG_HOME:-~/.config}` etc.
`:-` is a [bashism](https://en.wikipedia.org/wiki/Bash_(Unix_shell)#Portability) for variables with default values

**Comment by basxto** [comment]
Biggest plus would be, that one could simply paste paths from pcgamingwiki.
They use variables heavily for all platforms.

**Comment by MikeMaximus** [comment]
Yeah I was thinking about that last night actually.  They need to be changed.

**Comment by basxto** [comment]
This is also highly related to #148 
I couldn’t easily create a `%AppData%\megaglest\saves` on Linux for a Windows game.

I would have to type `/home/dabascht/.local/share\megaglest\saves`

**Comment by MikeMaximus** [comment]
I'm still tinkering with this between other work.  This is what I've done so far.

GBM now understands environment variables when creating configurations.  Linux understands some Windows environment variables(listed below), any variable listed by the "env" command in the format $HOME or $XDG_DATA_HOME, as well as the ~.  This will help when pasting a path directly from websites, terminal or file managers.  You always could use a GBM variable directly when creating a configuration, like *localappdata*\megaglest\saves would work, but I didn't have that documented anywhere.

GBM now uses Windows style environment variables instead of it's own (Ex. \*mydocs\*) when storing configurations paths.  I'm also using a [different method](https://docs.microsoft.com/en-us/dotnet/api/system.environment.expandenvironmentvariables?view=netframework-4.7.2)  of retrieving a path instead of converting them with my own function.

%LOCALAPPDATA% - Set by Windows, Set by GBM in Linux using .NET/Mono path.
%APPDATA% - Set by Windows, Set by GBM in Linux using .NET/Mono path.
%USERDOCUMENTS% - Set by GBM in both Windows and Linux using .NET/Mono path
%COMMONDOCUMENTS% - Set by GBM using .NET/Mono path, Mono has no path for this in Linux.
%USERPROFILE% - Set by Windows, Mono has no path for this in Linux. It uses "MyDocuments" instead.

Paths are still converted to the above variables for both Windows and Linux when a configuration is saved.

I'm still considering how I want to display paths in the Game Manager as well as differentiating Windows/Linux configurations.

**Comment by basxto** [comment]
Making Windows variables usable on Linux makes it harder to work with wine games, since they need to be resolved relative to the prefix.
I think most games have different paths on different platforms, so the helpfulness of this feature is very limited.
Wine games are rather the main use case for such variables.


> I'm still considering how I want to display paths in the Game Manager as well as differentiating Windows/Linux configurations.

Showing the true path when hovering the variable would be the most beautiful way … like it’s done on pcgamingwiki.
But that is likely not possible inside of an input field

**Comment by basxto** [comment]
Okay, `${XDG_DATA_HOME:-~/.local/share}` introduces recursion. I did not think of that.
But I’m mostly done with converting strings into Linux paths.
I removed GetUnixEnv() and instead transform variables into Windows format.
Invalid Linux variables will stay in Windows format, if I would convert them back I would destroy Windows variables for Wine.
`ReverseSpecialPaths` does if-else for Windows and Linux.
```
${XDG_DATA_HOME:-~/.local/share}/0ad/saves
~/3079Saves
~/.agen/8-Bit Commando/
../../ASAMU/Saves
${XDG_CONFIG_HOME:-~/.config}/A Wizard's Lizard/Local Storage
${XDG_CONFIG_HOME:-~/.config}/unity3d/Dejobaan Games/Awesome/
${XDG_CONFIG_HOME:-${XDG_CONFIG_HOME:-~/.config}}/A Wizard's Lizard/Local Storage                                                                             
${XDG_DATA_HOME:-${XDG_DATA_HOME:-~/.local/share}}/0ad/saves
~/3079Saves
```
The last three are with `mgrPath.ReverseSpecialPaths(mgrPath.ReverseSpecialPaths())`


```terminal
$ ls ${XDG_DATA_HOME:-~/.local/share}/0ad/saves
savegame-0001.0adsave  savegame-0002.0adsave  savegame-0003.0adsave  savegame-0004.0adsave     
```

I would honestly reduce ReverseSpecialPaths to just replacing the user directory, since that is the only thing that will be different on every PC. And also unify variable syntax for Linux, but I don’t think that is neccessary for Windows.

**Comment by MikeMaximus** [comment]
I was unsure about the syntax around the Linux variables and what I should do there.  I'm interested to see what you've done.

I've been considering just replacing the user directory.  The only consideration is that will break configurations for Windows XP, because it uses a different folder structure for Documents and AppData.  

But the amount of users still using XP and GBM is likely very low to nil.

**Comment by basxto** [comment]
I hacked around the recursion issue, I just don’t resolve `~` inside variables.
If it stays `${XDG_CONFIG_HOME:-~/.config}`, it won’t be touched because replace looks for `/home/dabascht/.config`

> The only consideration is that will break configurations for Windows XP

In the end it should reflect what the game uses.
If it’s note working for somebody, they might open an issue.
The thing is, if a game uses `%USERPROFILE%\AppData\Roaming` instead of `%APPDATA%`, it would be `C:\Documents and Settings\Username\AppData\Roaming` even on XP.
I think it’s on Linux more likely to appear, because I assume that some devs are not really sure what they are doing when they create their first Linux port.

> But the amount of users still using XP and GBM is likely very low to nil.

Thing with Wine is, I have a game from 2015 which wineHQ recommends running in 32-bit XP-mode.
Sometimes it’s just running better on older platforms because they are supported better by Wine.

**Comment by MikeMaximus** [comment]
The additions looks great basxto, Thanks.

>The thing is, if a game uses %USERPROFILE%\AppData\Roaming instead of %APPDATA%, it would be C:\Documents and Settings\Username\AppData\Roaming even on XP.

But on XP %APPDATA% is located in
`C:\Documents and Settings\Username\Application Data\`

The Documents folder structure on XP also uses "My Documents" instead of just "Documents" as it does in Win7+.  

It doesn't really hurt to leave it as it is, for now anyway.

**Comment by MikeMaximus** [comment]
![2018-09-08-115104_1920x1080_scrot](https://user-images.githubusercontent.com/15719732/45257165-e11ef400-b35e-11e8-912e-14efa66af222.jpg)

I think just a generic tooltip with the full path when hovered looks nice.  It disappears when working in the field and after 5 seconds.

**Comment by basxto** [comment]
Yes, that looks great

**Comment by MikeMaximus** [comment]
I'm prepping for the v1.1.5 release and looking over all changes.

In the database upgrade, when I convert configuration paths on Linux to the new path variables I'm doing the following.

```
sSQL = "UPDATE monitorlist SET Path = Replace(Path,'*appdatalocal*','${XDG_DATA_HOME:-~/.local/share}');"
sSQL &= "UPDATE monitorlist SET Path = Replace(Path,'*appdataroaming*','${XDG_CONFIG_HOME:-~/.config}');"
sSQL &= "UPDATE monitorlist SET Path = Replace(Path,'*mydocs*','~');"
```

@basxto Would ${HOME} be preferable to ~ when configurations refer to the Home folder?

**Comment by MikeMaximus** [comment]
Ok Thanks. I will leave it as ~.
