### ISSUE TITLE
Is there way to contribute to the official game list?

### ISSUE THREAD

**Issue by xKeiro** [MikeMaximus/gbm#154]
I think it would be a great if we could crowd source the games for the official list.

**Comment by basxto** [comment]
The way I do it:
* Fork [gbm-web](https://github.com/MikeMaximus/gbm-web)
* Export your game list to [GBM_Official.xml](https://github.com/MikeMaximus/gbm-web/blob/gh-pages/GBM_Official.xml) (or _Linux.xml)
* Filter for tag `Official`
* Make sure to add `<?xml-stylesheet type="text/xsl" href="GBM_Official.xsl"?>` (or _Linux.xsl) at line 2
* Check with `git diff` if you did not accidentally change something else
* Add, commit, push
* Pull request on github.

It should be exported with newest GBM version, since version is stored in the export.

If you are not familiar with git, maybe best idea is to open an issue on gbm-web, unless @MikeMaximus has other plans.
* Go to game
* Click “Game ID” and copy the ID
* Export
* Filter by Game ID
* Copy content of the `.xml` file to issue gated by \`\`\` or change extension to `.txt` and attach to issue

With a pull request it’s easier to reconstruct who added which game.

**Comment by MikeMaximus** [comment]
Basxto covered the current options.  You can also email exported XML files with games you'd like to add to gamebackupmonitor@gmail.com.  I may add some official method in the app at some point, but it's not on the horizon.
