### ISSUE TITLE
Checking save paths

### ISSUE THREAD

**Issue by basxto** [MikeMaximus/gbm#158]
How do you check, whether all necessary files are saved the backup?

I think I’ll use for now:
* Move whole configuration folder away
* Start game and check whether save games are gone
* Restore from backup
* Start game and  check whether save games are back

**Comment by MikeMaximus** [comment]
That's pretty much what I do.  

It's trickier to test old games that save multiple files directly into the game folder itself.  Interstate '76 for example,  what a pain.

**Comment by MikeMaximus** [comment]
I forgot to mention that.  I always keep Steam Cloud and GOG Galaxy Cloud Saves disabled so I don't even think about it.  

Right some new games still do it.  I still find it more annoying with older games since the naming schemes are usually more cryptic and it's harder to tell what is actually being saved to that file and if it's necessary.
