### ISSUE TITLE
Autostart on linux

### ISSUE THREAD

**Issue by basxto** [MikeMaximus/gbm#178]
This only works with desktop environments or tools who follow the [XDG autostart specification](https://standards.freedesktop.org/autostart-spec/autostart-spec-latest.html).
Therefore the naming on Linux should rather be `Autostart on XDG compliant desktop environments (KDE, GNOME etc.)`

Only ungrey the option if `/usr/share/applications/gbm.desktop` exists, because that means GBM is installed.
Check box if `~/.config/autostart/gbm.desktop` is found.

Enabling:
`ln -s /usr/share/applications/gbm.desktop ~/.config/autostart/`

Disabling:
`rm ~/.config/autostart/gbm.desktop`

**Comment by MikeMaximus** [comment]
Sounds fine.  I should probably also rename "Start to system tray" to something like "Start minimized or hidden" and enable that as well.

**Comment by MikeMaximus** [comment]
Unfortunately I can't find a reliable way for GBM to "Start Minimized" in Linux.  Mono doesn't seem to obey the rules when it comes how events are raised when a form is loaded.  I had a promising work-around, but it could cause Mono to crash in some situations so it's not worth it.

**Comment by MikeMaximus** [comment]
I've found a way for "Start Minimized" to work reliably in Linux, so that'll be ready for v1.1.8.  It wasn't an issue with Mono at all.  Mono actually forces you to do things properly because it crashes otherwise,  while .NET lets you be sloppy and get away with it.

I also added support for autostart when GBM is installed to /usr/local/share or /usr/share.
