### ISSUE TITLE
GBM tracks wine instead of process

### ISSUE THREAD

**Issue by basxto** [MikeMaximus/gbm#196]
I just started Galaxy with Wine and then ran The Witcher 3 from it.
GBM thinks the game is running until Galaxy is closed.

**Comment by MikeMaximus** [comment]
I'm not sure how Wine works when a child process is spawned. 

If it's using the same wine-preloader process to handle Galaxy and any games that are launched, then GBM won't be able to tell when the game ends because there's only one process for it to watch.

**Comment by MikeMaximus** [comment]
I don't have the means the properly research or a test a solution to this issue at the moment.

But I have a pretty good idea on how to fix this when I can get to work on it.

**Comment by MikeMaximus** [comment]
I can't replicate this behavior when I use something like the dos command prompt in Wine to start other processes in the same prefix and have GBM detect them.

If you get a chance, the following steps could help me figure out what it's doing.

1.  Use the build at this link: https://www.dropbox.com/s/gk8rgzh5mekg1kq/gbm%20process%20debug.7z?dl=0

2.  Press ```CTRL + ~``` on the main GBM window to bring up the debug console.

3.  Enter the command: ```debug process enable```

4.  Run Galaxy and Witcher 3, wait for GBM to detect Witcher 3.

5.  Show me the results of your ~/.local/share/gbm/gbm_process_list.txt and ~/.local/share/gbm/gbm_last_detected_process.txt after Witcher 3 is detected.  If you don't want to post information here, you can email it to gamebackupmonitor@gmail.com.

**Comment by basxto** [comment]
I’ll try it that weekend

**Comment by MikeMaximus** [comment]
I setup a test case for this using Galaxy 1.2.5.9 and Cultist Simulator.  I can't get the 2.0 beta to work in Wine, I should have verified the version you were using.  

The following processes get spawned when I launch the game.

```
9383 wine-preloader C:\Program Files (x86)\GOG Galaxy\Games\Cultist Simulator\cultistsimulator.exe                                                                                                               
9390 wine-preloader C:\Program Files (x86)\GOG Galaxy\Games\Cultist Simulator\UnityCrashHandler32.exe --attach 724 3805184                                                                                                               
9420 wine-preloader C:\ProgramData\GOG.com\Galaxy\redists\overlay\GalaxyOverlay.exe --advanced-features --startoverlay --startup-url=file:///C:/Program%20Files%20(x86)/GOG%20Galaxy/web/overlay.html --product-id=1456702644 --client-language-code=en-US --attached-pid=724 --cache-path=C:\ProgramData\GOG.com\Galaxy\webcache\1456702644-overlay --screenshot-path=C:\users\mike\My Documents\GOG Galaxy\Screenshots\Cultist Simulator
```
It works in this scenario and properly watches PID 9383, but it's given me some insight to what may be happening.  

GBM may be watching the wrong wine-preloader process (a Galaxy sub-process) because it's command contains simply contains a reference to "witcher3" and it's the first one detected, but I'm not sure what that would be and why it doesn't end when you close the game.

Your process debug output will likely shed some light on it.  I know it's the holidays and no rush! I just wanted to give an update since I finally got around to setting up a test scenario myself.

**Comment by MikeMaximus** [comment]
Closing this issue until more information is available,  I haven't been able to replicate on my Linux install.  

The current release version has the debug mode fixes so the special version listed above is no longer required.
