### ISSUE TITLE
[Bug] Save Path selection window does not allow folder selection

### ISSUE THREAD

**Issue by Darthagnon** [MikeMaximus/gbm#201]
When browsing for a game's save path via the [...] button, for the Save Path box, the title of the Explorer window that opens is "Choose the saved game folder:". Unfortunately, only file selection is possible. So far, I'm working around it by typing in the save folder paths manually. Ticking the "save entire folder" checkbox makes no difference.

**Comment by MikeMaximus** [comment]
I looked into this a bit more tonite.  

I was able to get it into a state where it wouldn't even select the current folder.  And being a hack it's already confusing enough.

Sorry about that, i'll see what i can do for the next update.

**Comment by Darthagnon** [comment]
Thank you for testing it out, and for making this amazing software! I just tested out folder selection as per your first comment, and managed to get it to work! I think I must have always had a folder selected before or something, which was why I was unable to "Open" the current folder (which is usable imo).

**Comment by MikeMaximus** [comment]
Glad it's working for you now. 👍 

Yes the problem is when a folder is selected, as the default action for the control is to open it instead of selecting it.  And sometimes when performing certain actions, like moving up a level, a folder will be automatically selected and you get stuck in a loop of opening it rather than selecting it.

There doesn't seem to much I can do about that without over-complicating things and possibly cause problems with the control in Mono.  

I am going to change the text of the explorer window to be a little more concise, something like "Browse to saved game folder and click Open"

**Comment by Darthagnon** [comment]
Wondering, is it possible to change the text on the "Open" button to "Select" or "Select folder"? Or is that one of the limitations of Windows' (bad) selection dialog?

**Comment by MikeMaximus** [comment]
In terms of how the dialog looks, all I have easy control over is the window title.

Unfortunately .NET exposes very little for customizing File Open/Save dialogs.  There are ways around it, such as creating my own version of the dialog or using more complex hacks to modify it.  But that all involves more time and testing than i'd want to commit to one specific issue.
