### ISSUE TITLE
Metro Exodus seems to have 2 Game IDs considered valid

### ISSUE THREAD

**Issue by redactedscribe** [MikeMaximus/gbm#243]
Importing Metro Exodus via the Official List adds a Metro Exodus entry with Game ID `8ac11c11-8d18-471b-8f0d-aa154dc77f0e`.

Using the Sync Game IDs via Official List function reports "1 game configurations were matched and updated.".

Game ID for Metro Exodus has now changed to `4080571c-59da-4555-a2c4-63b82622522b`.

Importing again shows two Metro Exoduses, one with an update symbol, and another with a the newly detected `+` symbol. Importing the new/plus one creates a _second_ Metro Exodus entry in the list of games, but with the original Game ID of `8ac11c11-8d18-471b-8f0d-aa154dc77f0e` again.

The values (paths, etc) for each game appear to be identical. It seems something is out of sync -- and maybe for more than one game in the Official List.

GBM v1.2.8

**Comment by MikeMaximus** [comment]
The official game list has different game configurations with the same name.  This is due to games being released on multiple store platforms with different builds, which save to different locations.  The Metro Exodus configurations are not identical,  one is for Windows Store and the other is for platforms that use a different saved game path.

http://mikemaximus.github.io/gbm-web/GBM_Official.xml#?q=id:4080571c-59da-4555-a2c4-63b82622522b
http://mikemaximus.github.io/gbm-web/GBM_Official.xml#?q=id:8ac11c11-8d18-471b-8f0d-aa154dc77f0e

"Sync Game IDs" is a optional tool that was designed to be only used after updating from old GBM versions in which the game "Game ID" field did not exist, and it should only be used for that reason. It attempts to sync your current game list to the current official list based on "Name" only.

The "Sync Game IDs" tool will be completely removed in the next version or perhaps the following one, it's just provided for compatibility reasons for anyone upgrading from very old builds.
