### ISSUE TITLE
Dont create Backup on Game name

### ISSUE THREAD

**Issue by Scoty43** [MikeMaximus/gbm#271]
No backup is made based on the game name, but cryptic names are created.

Whene i make a backup from Far Cry 6 the save game folder named 4bf14940-7d60-445d-9a7c-14e176a4f106.

**Comment by MikeMaximus** [comment]
Hello,

The cryptic name is the unique Game ID.

Do you have multiple game configurations using the name "Far Cry 6"?  If so, this is why the Game ID is being used for folder/file names instead of the Game Name.  

This is done to prevent backup configurations with the same name from overwriting each other.  To stop this from happening, you can either rename or delete the other configuration(s) named Far Cry 6, then the next backup will use the Game Name instead of the Game ID.

If that doesn't help let me know and I'll have to see if it's a bug.

**Comment by Darthagnon** [comment]
Would it be possible to use `Game Name (2)`, kinda like the way Windows does it? That's at least more human-readable than a UUID.

**Comment by MikeMaximus** [comment]
Using simple numbers like Windows is more human-readable but also makes it more difficult to track which configuration the backup actually belongs to.

The next release will use the format "Far Cry 6 [8ac11c11-8d18-471b-8f0d-aa154dc77f0e]" instead of just the Game ID when duplicate configurations are encountered.

There may also be other changes being discussed in #272.
