### ISSUE TITLE
Issue: GBM creates "ghost window" when minimized to tray on Linux (KDE Plasma, at least)

### ISSUE THREAD

**Issue by laribA** [MikeMaximus/gbm#303]
Issue occurred on Manjaro and Debian 12. KDE Plasma on both occasions.
When GBM starts up, if it is "minimized to the system tray", an icon does appear there, but in addition, GBM creates a "ghost window". This window does not appear in the taskbar, but it does distractingly appear in the Alt-Tab window menu, and in the Task View. Ideally this window would not exist, and would only pop up if the GUI is purposely opened.
I've attached a screenshot to better visualize what I mean.
![image](https://github.com/MikeMaximus/gbm/assets/64703812/bf574f01-e50d-4547-b56d-e5ae77f26604)

**Comment by MikeMaximus** [comment]
Thanks for the report laribA.

I did notice this when testing the last release with Mint 21 Cinnamon, I'm just not sure what I can do about it.  It was fine the last time I had tested it and none of my recent updates would have touched that code.  Mono has always had strange issues recurring issues when changing the visibility of a form.

On Mint if I just close the ghost window by clicking X, it does hide and show normally from the system tray after that.  I'll take a look before next release and see if I can do some kind of work-around.

**Comment by MikeMaximus** [comment]
I made a small work-around that seemed to fix this.  I'll probably do a maintenance release next month so you won't have to wait too long for the fix.

**Comment by MikeMaximus** [comment]
In v1.3.8 release testing this is still happening,  just not 100% of the time. 🤦‍♂️ 

Delaying v1.3.8 release until I see what else I can do about this.

**Comment by MikeMaximus** [comment]
This should be fixed now in the v138 release.  After trying a bunch of different little hacks I finally found something that seemed to fix it 100% of the time.

Please re-open the issue if you're still experiencing this problem after installing v138.

**Comment by laribA** [comment]
I'm sorry to do this, but I am still experiencing this problem after installing v1.3.8.
Nothing has changed, except for the fact I am on Ubuntu now. Still KDE Plasma.

**Comment by MikeMaximus** [comment]
I have to apologize.  I initially confused the issue you were having with another closely related one, likely because I looked at the screenshot and skimmed the rest of your initial post while working on something else.

There is also an issue with the ghost window getting stuck on the screen when the app initially starts with the "Start minimized" option enabled.  This was a problem across multiple desktop environments and is what I tried to fix in v1.3.8.

The KDE Plasma issue with the ghost window appearing in the task view / alt-tab menu while hidden is something I don't really have any control over.  Unfortunately Mono has many and completely different UI glitches across various desktop environments and all I can do is try and work-around the most offensive ones without breaking something else.
