### ISSUE TITLE
Searching by tags requires prepending '#'

### ISSUE THREAD

**Issue by Darthagnon** [MikeMaximus/gbm#309]
I was testing for #308, and thought my tags weren't working for a minute, until I realised that I needed to prepend '#' to search by a tag. As the tags are created in without '#' (and # used just as a visual identifier), would it be possible to make the search a little more flexible, and accept searching by the tag with or without the prepended '#'?

**Comment by MikeMaximus** [comment]
It did work like that initially, then I changed it to require a hashtag because it was suggested to do so for more accurate results based on game name or tag only.

If I do as you suggested in #308 and make it an even wider search by adding other fields, then I'll revert this back to not requiring the hashtag.

**Comment by MikeMaximus** [comment]
I've made some improvements to the quick search that I hope can satisfy everyone.  Here's a current rundown.

- Improved quick search (Main Window and Game Manager)
	- The default quick search is now wide, using most text fields and tags.
		- These fields currently include: Name, Process, Parameter, Path, Version, Company, Comments.
	- You can now do a refined quick search by prepending it with the field name and a colon.  Ex.  Name:Doom or Company:Sega
	- A refined tag search is still supported by prepending with a hashtag, Ex. #GOG
	- You cannot combine refined searches in a single quick search, use the "Custom Filter" on the Game Manager for complex queries.
