### ISSUE TITLE
Check available disk space

### ISSUE THREAD

**Issue by basxto** [MikeMaximus/gbm#78]
Check whether the target has enough space for storing the unencrypted gamesaves, otherwise p7zip will just throw an E_FAIL, which isn’t very informative.

Distribution: Archlinux
Kernel: 4.11.3
mono: 5.0.0.100
mono-basic: 4.6
p7zip: 16.02
sqlite: 3.19.3
bash: 4.4.012

**Comment by MikeMaximus** [comment]
Yes it should check this instead of letting 7z fail.  Thanks for the report.

**Comment by MikeMaximus** [comment]
GBM now does the following during a prerequisite check for a backup.

1.  Checks and displays available disk space of the backup drive in the log.
2   Checks and displays uncompressed size of the saved game folder in the log.
3.  Displays a warning if there may not be enough disk space and allows you to proceed if you want to.

**Comment by basxto** [comment]
Thank you for closing those issues so quickly.

**Comment by MikeMaximus** [comment]
I've been doing some testing and I noticed that GBM is always a bit off with it's folder size calculation when compared to what 7za is reporting.  It's because 7za reports the actual file size on disk, and GBM is reporting the logical size.

I just wanted to update this issue in case anyone else notices this.

I looked into having GBM calculate the actual file size on disk.  But it turns out to be a bigger pain than you'd think and the solution likely wouldn't work in both Windows and Linux.
